[theme]
primaryColor = "#4A90E2"          # A calm blue for highlights
backgroundColor = "#EAEAEA"       # Light gray for the background
secondaryBackgroundColor = "#B0B0B0"  # Medium gray for subtle contrast

